version: "3.9"
# 
services:
  backend:
    build: ./backend
    ports:
    - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
    networks:
      - es-net
    depends_on:
      - db
      - kibana

  server_par:
    build: ./server_par
    ports:
    - "8001:8001"
    env_file:
      - ./server_par/.env
    volumes:
      - ./server_par:/server_par
    networks:
      - es-net

    depends_on:
      - db
      - kibana
  
  client:
    build: ./frontend/
    ports:
    - "3000:3000"
    networks:
    - es-net
    volumes:
    - ./frontend:/user/src/app
    depends_on:
    - backend

  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - ./backend/.env
    networks:
      - es-net

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - "9200:9200"
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

networks:
  es-net:
    driver: bridge