version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - "9200:9200"
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  db:
    image: postgres:15
    container_name: db
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  es-net:
    driver: bridge






# version: "3.9"

# services:
  # server:
  #   build: .\server 
  #   ports:
  #   - "8000:8000"
  #   volumes:
  #     - .\server:\app
  # web:
  #   build: .\client
  #   ports:
  #   - "8081:8081"
  #   volumes:
  #   - .\client:\user\src\app
  #   depends_on:
  #   - server

