FROM python:3.11

RUN mkdir /fastapi_app

WORKDIR /fastapi_app
# 
COPY requirements.txt .

RUN apt-get update && apt-get install -y --no-install-recommends gcc \
    && pip install --no-cache-dir -r requirements.txt \
    && apt-get remove -y gcc \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

COPY  . .

WORKDIR /src


CMD ["uvicorn", "fastapi_app/src.main:app", "--host", "0.0.0.0", "--port", "81"]