# tg_name = 'ParserBot'
# tg_api_id = 13098476
# tg_api_hash = '0be3336d4f492ad5bd5a6fe66cdfc89d'

tg_name = 'Stephen'
tg_api_id = 23446137
tg_api_hash = 'e6859e20ab63752f8fe50b490a302f42'

CHANNELS = [
            # Новости и СМИ
            'https://t.me/novosti_voinaa',
            'https://t.me/rian_ru',
            'https://t.me/readovkanews',
            'https://t.me/breakingmash',
            'https://t.me/bbbreaking',
            'https://t.me/ostorozhno_novosti',
            'https://t.me/varlamov_news',
            'https://t.me/meduzalive',
            'https://t.me/wargonzo',
            'https://t.me/gosuslugi',
            # Технологии
            'https://t.me/Wylsared',
            'https://t.me/exploitex',
            'https://t.me/chatgpt1337tg',
            'https://t.me/naebnet',
            'https://t.me/milord_q',
            'https://t.me/habr_chatgpt_midjourney',
            'https://t.me/Romancev768',
            'https://t.me/bugfeature',
            'https://t.me/whackdoor',
            'https://t.me/DeepFaker',
            # Экономика
            'https://t.me/AlfaBank',
            'https://t.me/sberbank',
            'https://t.me/suverenka',
            'https://t.me/tinkoff_invest_official',
            'https://t.me/multievan',
            'https://t.me/omyinvestments',
            'https://t.me/banksta',
            'https://t.me/Coin_Post',
            'https://t.me/bitkogan',
            'https://t.me/bankrollo',
            'https://t.me/cb_economics',
            # Криптовалюта
            'https://t.me/Obmennik_obmenbtc',
            'https://t.me/cryptogram_ton',
            'https://t.me/toncoin_rus',
            'https://t.me/crypto_mozgi',
            'https://t.me/ARUTAcademy',
            # Путешествия
            'https://t.me/PobedaAirlines',
            'https://t.me/fpcrussia',
            'https://t.me/vandroukiru',
            'https://t.me/sitnikova_travel',
            'https://t.me/mikearoundtheworld',
            # Психология
            'https://t.me/its_woman_world',
            'https://t.me/psiho_logy',
            'https://t.me/top_sovett',
            'https://t.me/Psychologs',
            'https://t.me/psyxo1',
            # Дизайн
            'https://t.me/designdealer',
            'https://t.me/photosed',
            'https://t.me/figmaplugin',
            'https://t.me/AETemp',
            'https://t.me/photoshop_hack',
            # Политика
            'https://t.me/RKadyrov_95',
            'https://t.me/RVvoenkor',
            'https://t.me/SolovievLive',
            'https://t.me/rybar',
            'https://t.me/medvedev_telegram',
            'https://t.me/vv_volodin',
            'https://t.me/MDaudov_95',
            'https://t.me/adelimkhanov_95',
            'https://t.me/boris_rozhin',
            'https://t.me/dmitrynikotin',
            # Образование
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            '',
            ''
            ]