/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 tg.glb --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Camera_1_PhoneFace_Mat_0: THREE.Mesh
    Camera_2_PhoneFace_Mat_0: THREE.Mesh
    Camera_Front_PhoneButton_Mat_0: THREE.Mesh
    Camera_Light_Camera_Light1_0: THREE.Mesh
    Phone_Camera_PhoneCase_Mat_0: THREE.Mesh
    Phone_Case_PhoneCase_Mat_0: THREE.Mesh
    Phone_Case_PhoneFace_Mat_0: THREE.Mesh
    Plane: THREE.Mesh
    Power_Button_PhoneButton_Mat_0: THREE.Mesh
    Volume_Down_PhoneButton_Mat_0: THREE.Mesh
    Volume_Up_PhoneButton_Mat_0: THREE.Mesh
    ['Cylinder_��������������_0']: THREE.Mesh
    Cylinder001_Material002_0: THREE.Mesh
    Cylinder002_Material001_0: THREE.Mesh
    Cylinder002_Material003_0: THREE.Mesh
    Cylinder003_Material002_0: THREE.Mesh
    Cylinder004_Material002_0: THREE.Mesh
    Cylinder005_Material002_0: THREE.Mesh
    ['Cylinder005_��������������_0']: THREE.Mesh
    Cylinder006_Material002_0: THREE.Mesh
    ['Cylinder006_��������������_0']: THREE.Mesh
    Cylinder007_Material001_0: THREE.Mesh
    Cylinder007_Material003_0: THREE.Mesh
    Cylinder008_Material001_0: THREE.Mesh
    Cylinder008_Material003_0: THREE.Mesh
    Cylinder009_Material002_0: THREE.Mesh
    Cylinder010_Material002_0: THREE.Mesh
    ['Cylinder011_��������������_0']: THREE.Mesh
    Cylinder012_Material002_0: THREE.Mesh
    ['Cylinder013_��������������_0']: THREE.Mesh
    ['Cylinder014_��������������_0']: THREE.Mesh
    ['Cylinder015_��������������_0']: THREE.Mesh
    ['Cylinder016_��������������_0']: THREE.Mesh
    Cylinder017_Material002_0: THREE.Mesh
    Cylinder018_Material002_0: THREE.Mesh
    Cylinder019_Material002_0: THREE.Mesh
    ['Cylinder020_��������������_0']: THREE.Mesh
    ['Cylinder021_��������������_0']: THREE.Mesh
    ['Cylinder022_��������������_0']: THREE.Mesh
    Cylinder034_Material002_0: THREE.Mesh
    ['Cylinder034_��������������_0']: THREE.Mesh
    Cylinder035_Material002_0: THREE.Mesh
    ['Cylinder035_��������������_0']: THREE.Mesh
    Cylinder036_Material001_0: THREE.Mesh
    Cylinder036_Material003_0: THREE.Mesh
    Cylinder037_Material001_0: THREE.Mesh
    Cylinder037_Material003_0: THREE.Mesh
    Cylinder038_Material002_0: THREE.Mesh
    ['Cylinder038_��������������_0']: THREE.Mesh
    Cylinder039_Material002_0: THREE.Mesh
    ['Cylinder040_��������������_0']: THREE.Mesh
    Cylinder041_Material002_0: THREE.Mesh
    ['Cylinder042_��������������_0']: THREE.Mesh
    ['Cylinder043_��������������_0']: THREE.Mesh
    ['Cylinder044_��������������_0']: THREE.Mesh
    ['Cylinder045_��������������_0']: THREE.Mesh
    Cylinder046_Material002_0: THREE.Mesh
    Cylinder047_Material002_0: THREE.Mesh
    Cylinder048_Material002_0: THREE.Mesh
    ['Cylinder049_��������������_0']: THREE.Mesh
    ['Cylinder050_��������������_0']: THREE.Mesh
    ['Cylinder051_��������������_0']: THREE.Mesh
    Cylinder052_Material001_0: THREE.Mesh
    Cylinder052_Material001_0001: THREE.Mesh
    Cylinder052_Material002_0: THREE.Mesh
    Cylinder052_Material003_0: THREE.Mesh
    Cylinder052_Material003_0001: THREE.Mesh
    ['Cylinder052_��������������_0']: THREE.Mesh
    Cylinder058_Material002_0: THREE.Mesh
    Cylinder058_Material002_0001: THREE.Mesh
    Cylinder059_Material002_0: THREE.Mesh
    Cylinder059_Material002_0001: THREE.Mesh
    ['Cylinder059_��������������_0']: THREE.Mesh
    ['Cylinder059_��������������_0001']: THREE.Mesh
    Sphere_1: THREE.Mesh
    Sphere_2: THREE.Mesh
    Sphere_3: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder063: THREE.Mesh
    Sphere001: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder001_1: THREE.Mesh
    Sphere002: THREE.Mesh
    Text: THREE.Mesh
    Text001: THREE.Mesh
    Text002: THREE.Mesh
  }
  materials: {
    PhoneFace_Mat: THREE.MeshStandardMaterial
    PhoneButton_Mat: THREE.MeshStandardMaterial
    Camera_Light1: THREE.MeshStandardMaterial
    PhoneCase_Mat: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/tg.glb') as GLTFResult
  return (
    <group {...props} position={[0, -1.75, 0]} dispose={null}>
      <group position={[-0.75, 2.622, 0.546]} rotation={[-1.12, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[17.768, 52.313, -26.907]} rotation={[Math.PI / 4, 0, 0]} scale={1.696}>
            <mesh geometry={nodes.Camera_1_PhoneFace_Mat_0.geometry} material={materials.PhoneFace_Mat} position={[0, 3.776, 1.312]} />
          </group>
          <group position={[17.768, 49.052, -23.646]} rotation={[Math.PI / 4, 0, 0]} scale={1.696}>
            <mesh geometry={nodes.Camera_2_PhoneFace_Mat_0.geometry} material={materials.PhoneFace_Mat} position={[0, 3.776, 1.312]} />
          </group>
          <group position={[14.855, 50.704, -25.298]} rotation={[Math.PI / 4, 0, 0]} scale={0.875}>
            <mesh geometry={nodes.Camera_Light_Camera_Light1_0.geometry} material={materials.Camera_Light1} position={[0, 7.321, 2.543]} />
          </group>
          <group position={[16.445, 51.196, -24.719]} rotation={[Math.PI / 4, 0, 0]} scale={[0.889, 1, 1]}>
            <mesh geometry={nodes.Phone_Camera_PhoneCase_Mat_0.geometry} material={materials.PhoneCase_Mat} position={[0, 6.403, 2.224]} />
          </group>
          <group position={[0, 43.978, 0]} rotation={[Math.PI / 4, 0, 0]}>
            <mesh geometry={nodes.Phone_Case_PhoneCase_Mat_0.geometry} material={materials.PhoneCase_Mat} position={[8.025, -3.051, 2]} />
            <mesh geometry={nodes.Phone_Case_PhoneFace_Mat_0.geometry} material={materials.PhoneFace_Mat} position={[8.025, -24.129, 23.078]}>
              <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[-0.745, 22.854, -23.54]} rotation={[0.004, 0, 0]} scale={9.053} />
            </mesh>
          </group>
          <group position={[23.265, 48.168, -17.296]} rotation={[Math.PI / 4, 0, 0]} scale={[1, 1, 1.24]}>
            <mesh geometry={nodes.Power_Button_PhoneButton_Mat_0.geometry} material={materials.PhoneButton_Mat} position={[0, 6.259, 1.753]} />
          </group>
          <group position={[-7.096, 44.591, -14.14]} rotation={[0.787, 0, -3.053]} scale={[1, 1, 0.793]}>
            <mesh geometry={nodes.Volume_Down_PhoneButton_Mat_0.geometry} material={materials.PhoneButton_Mat} position={[-0.566, -6.382, 2.788]} />
          </group>
          <group position={[-7.097, 47.965, -17.501]} rotation={[0.787, 0, -3.053]} scale={[1, 1, 0.793]}>
            <mesh geometry={nodes.Volume_Up_PhoneButton_Mat_0.geometry} material={materials.PhoneButton_Mat} position={[-0.566, -6.382, 2.789]} />
          </group>
          <mesh geometry={nodes.Camera_Front_PhoneButton_Mat_0.geometry} material={materials.PhoneButton_Mat} position={[7.603, 59.666, -25.535]} rotation={[Math.PI / 4, 0, 0]} scale={0.575} />
        </group>
      </group>
      <group position={[0.797, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Cylinder_��������������_0'].geometry} material={materials.material} position={[0.007, -0.01, 2.906]} rotation={[0.068, -0.168, -0.467]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder002_Material001_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cylinder002_Material003_0.geometry} material={materials['Material.004']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder005_Material002_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes['Cylinder005_��������������_0'].geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder006_Material002_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes['Cylinder006_��������������_0'].geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder007_Material001_0.geometry} material={materials['Material.002']} position={[-1.019, -0.136, 2.835]} rotation={[0, 0, 0.432]} />
            <mesh geometry={nodes.Cylinder007_Material003_0.geometry} material={materials['Material.004']} position={[-0.855, -0.057, 2.754]} rotation={[0, 0, 0.432]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder008_Material001_0.geometry} material={materials['Material.002']} position={[-1.652, -0.684, 3.42]} rotation={[0, 0, 0.646]} />
            <mesh geometry={nodes.Cylinder008_Material003_0.geometry} material={materials['Material.004']} position={[-1.586, -0.602, 3.34]} rotation={[0, 0, 0.646]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder009_Material002_0.geometry} material={materials['Material.003']} position={[-1.214, -0.233, 2.961]} rotation={[0, 0, 0.293]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder010_Material002_0.geometry} material={materials['Material.003']} position={[-1.847, -0.919, 3.648]} rotation={[0.046, -0.035, 0.583]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Cylinder011_��������������_0'].geometry} material={materials.material} position={[-1.789, -1.088, 3.882]} rotation={[0.481, 0.134, -0.108]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder012_Material002_0.geometry} material={materials['Material.003']} position={[-1.787, -1.158, 3.96]} rotation={[0.501, -0.174, -0.256]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Cylinder013_��������������_0'].geometry} material={materials.material} position={[-1.851, -1.214, 4.003]} rotation={[0.588, -0.637, -0.648]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Cylinder014_��������������_0'].geometry} material={materials.material} position={[0.198, -0.767, 0.058]} rotation={[-0.011, 0, 0]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Cylinder015_��������������_0'].geometry} material={materials.material} position={[0.189, -0.794, 0.096]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Cylinder016_��������������_0'].geometry} material={materials.material} position={[0.206, -0.751, 0.088]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder017_Material002_0.geometry} material={materials['Material.003']} position={[0.198, -0.767, 0.058]} rotation={[-0.011, 0, 0]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder018_Material002_0.geometry} material={materials['Material.003']} position={[0.189, -0.794, 0.096]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder019_Material002_0.geometry} material={materials['Material.003']} position={[0.206, -0.751, 0.088]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Cylinder020_��������������_0'].geometry} material={materials.material} position={[0.198, -0.767, 0.058]} rotation={[-0.011, 0, 0]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Cylinder021_��������������_0'].geometry} material={materials.material} position={[0.189, -0.794, 0.096]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Cylinder022_��������������_0'].geometry} material={materials.material} position={[0.206, -0.751, 0.088]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder034_Material002_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes['Cylinder034_��������������_0'].geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder035_Material002_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes['Cylinder035_��������������_0'].geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder036_Material001_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cylinder036_Material003_0.geometry} material={materials['Material.004']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder037_Material001_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cylinder037_Material003_0.geometry} material={materials['Material.004']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder038_Material002_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes['Cylinder038_��������������_0'].geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder052_Material001_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Cylinder052_Material001_0001.geometry} material={materials['Material.002']} position={[-0.007, 0, 0.041]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes.Cylinder052_Material002_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cylinder052_Material003_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Cylinder052_Material003_0001.geometry} material={materials['Material.004']} position={[-0.007, 0, 0.041]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes['Cylinder052_��������������_0'].geometry} material={materials.material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder058_Material002_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cylinder058_Material002_0001.geometry} material={materials['Material.003']} position={[-0.007, 0, 0.041]} rotation={[0, 0, -Math.PI]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cylinder059_Material002_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Cylinder059_Material002_0001.geometry} material={materials['Material.003']} position={[-0.007, 0, 0.041]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes['Cylinder059_��������������_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['Cylinder059_��������������_0001'].geometry} material={materials.material} position={[-0.009, 0, 0.045]} rotation={[0, 0, -Math.PI]} />
          </group>
          <mesh geometry={nodes.Cylinder001_Material002_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder003_Material002_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder004_Material002_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder039_Material002_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Cylinder040_��������������_0'].geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder041_Material002_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Cylinder042_��������������_0'].geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Cylinder043_��������������_0'].geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Cylinder044_��������������_0'].geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Cylinder045_��������������_0'].geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder046_Material002_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder047_Material002_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder048_Material002_0.geometry} material={materials['Material.003']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Cylinder049_��������������_0'].geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Cylinder050_��������������_0'].geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes['Cylinder051_��������������_0'].geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[0.797, 2.561, 0]} scale={[0.673, 0.57, 0.491]}>
        <mesh geometry={nodes.Sphere_1.geometry} material={materials['Material.011']} />
        <mesh geometry={nodes.Sphere_2.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Sphere_3.geometry} material={materials['Material.013']} />
      </group>
      <group position={[0.577, 2.697, 0.415]} rotation={[Math.PI / 2, 0, 0]} scale={[0.153, 0.064, 0.153]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes.Cylinder063.geometry} material={materials['Material.010']} position={[0.779, 2.33, 0.466]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.027, 0.202, 0.027]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.009']} position={[0.573, 2.696, 0.394]} scale={0.102} />
      <group position={[1.025, 2.707, 0.415]} rotation={[Math.PI / 2, 0, 0]} scale={[0.153, 0.064, 0.153]}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.009']} position={[1.021, 2.707, 0.394]} scale={0.102} />
      <mesh geometry={nodes.Text.geometry} material={materials.Material} position={[0.859, 2.647, -0.494]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.217} />
      <mesh geometry={nodes.Text001.geometry} material={materials.Material} position={[1.19, 2.477, -0.49]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.373, 0.373, 0.381]} />
      <mesh geometry={nodes.Text002.geometry} material={materials.Material} position={[0.716, 1.645, 0.377]} rotation={[1.411, 0, 0]} scale={[0.184, 0.184, 0.188]} />
    </group>
  )
}

useGLTF.preload('/tg.glb')
