"""NewsTG

Revision ID: ad021141598e
Revises: d4ff5219f736
Create Date: 2023-10-09 22:54:53.328161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad021141598e'
down_revision = 'd4ff5219f736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
