"""NewsTG

Revision ID: d4ff5219f736
Revises: 
Create Date: 2023-10-08 23:46:55.268121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ff5219f736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_data',
    sa.Column('tg_data_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('sender', sa.Text(), nullable=True),
    sa.Column('chat_title', sa.Text(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('photo_id', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('tg_data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_data')
    # ### end Alembic commands ###
